version: "2"
name: "VerilogOJServices"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "1234:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  service0:
    build:
      context: ./services/${service0_name}
      dockerfile: Dockerfile
    image: ${services_namespace}_${service0_name}:v1
    container_name: ${services_namespace}_${service0_name}
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${services_namespace}.${service0_name}
      - VIRTUAL_PORT=80

  service1:
    build:
      context: ./services/${service1_name}
      dockerfile: Dockerfile
    image: ${services_namespace}_${service1_name}:v1
    container_name: ${services_namespace}_${service1_name}
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${services_namespace}.${service1_name}
      - VIRTUAL_PORT=80
