version: "2"
name: "VerilogOJServices"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: ${services_namespace}_nginxproxy

    ports:
      - "${host_port}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  service0:
    build:
      context: ./services/${service0_name}
      dockerfile: Dockerfile
    image: ${services_namespace}_${service0_name}:v1
    container_name: ${services_namespace}_${service0_name}

    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${services_namespace}.${service0_name}
      - VIRTUAL_PORT=80

  service1:
    build:
      context: ./services/${service1_name}
      dockerfile: Dockerfile
    image: ${services_namespace}_${service1_name}:v1
    container_name: ${services_namespace}_${service1_name}
    
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${services_namespace}.${service1_name}
      - VIRTUAL_PORT=80

  service2:
    build:
      context: ./services/${service2_name}
      dockerfile: Dockerfile
    image: ${services_namespace}_${service2_name}:v1
    container_name: ${services_namespace}_${service2_name}
    
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${services_namespace}.${service2_name}
      - VIRTUAL_PORT=80

  service3:
    build:
      context: ./services/${service3_name}
      dockerfile: Dockerfile
    image: ${services_namespace}_${service3_name}:v1
    container_name: ${services_namespace}_${service3_name}
    
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${services_namespace}.${service3_name}
      - VIRTUAL_PORT=80

  service4:
    build:
      context: ./services/${service4_name}
      dockerfile: Dockerfile
    image: ${services_namespace}_${service4_name}:v1
    container_name: ${services_namespace}_${service4_name}
    
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=${services_namespace}.${service4_name}
      - VIRTUAL_PORT=80
